# Generated by Django 3.1.2 on 2020-10-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_no',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='問題No.'),
        ),
    ]
