# Generated by Django 3.1.2 on 2020-10-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_question_question_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_choice_no',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='正解No.'),
        ),
    ]
