# Generated by Django 3.1.2 on 2020-10-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20201022_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='body_kana',
            field=models.CharField(default='', max_length=1024, verbose_name='本文（ひらがな）'),
        ),
        migrations.AddField(
            model_name='textchoice',
            name='body_kana',
            field=models.CharField(default='', max_length=1024, verbose_name='選択肢（ひらがな）'),
        ),
        migrations.AlterField(
            model_name='question',
            name='body',
            field=models.CharField(max_length=1024, verbose_name='本文（漢字）'),
        ),
        migrations.AlterField(
            model_name='textchoice',
            name='body',
            field=models.CharField(max_length=512, verbose_name='選択肢（漢字）'),
        ),
    ]
