# Generated by Django 3.1.2 on 2020-10-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20201022_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='Category',
        ),
        migrations.AddField(
            model_name='question',
            name='Category',
            field=models.ManyToManyField(to='question.Category'),
        ),
    ]
