# Generated by Django 3.1.2 on 2020-10-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_auto_20201022_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='comment',
            field=models.CharField(default='', max_length=1024, verbose_name='解説'),
        ),
    ]
