# Generated by Django 3.1.2 on 2020-11-03 07:15

from django.db import migrations, models
import django.db.models.deletion
import question.models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_auto_20201103_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='disp_type',
            field=models.ForeignKey(default=question.models.set_default_disp_type, on_delete=django.db.models.deletion.SET_DEFAULT, to='question.disptype'),
        ),
    ]
