# Generated by Django 3.1.2 on 2020-11-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_question_disp_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDispType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='表示形式名')),
            ],
        ),
    ]
