# Generated by Django 3.1.2 on 2020-11-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0013_auto_20201103_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='avator',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='avator'),
        ),
    ]
