# Generated by Django 3.1.2 on 2020-11-03 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0014_question_avator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1024, verbose_name='本文（漢字）')),
                ('body_kana', models.CharField(default='', max_length=1024, verbose_name='本文（ひらがな）')),
                ('question_no', models.PositiveSmallIntegerField(default=0, verbose_name='問題No.')),
                ('answer_choice_no', models.PositiveSmallIntegerField(default=1, verbose_name='正解No.')),
                ('ok_comment', models.CharField(default='', max_length=1024, verbose_name='解説（正解の場合）')),
                ('ng_comment', models.CharField(default='', max_length=1024, verbose_name='解説（不正解の場合）')),
                ('Category', models.ManyToManyField(to='question.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ImageChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='images/', verbose_name='avator')),
                ('choice_no', models.PositiveSmallIntegerField(default=1, verbose_name='選択肢No.')),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
            ],
        ),
    ]
