# Generated by Django 3.1.2 on 2020-11-03 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0015_imagechoice_imagequestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagechoice',
            name='Question',
        ),
        migrations.AddField(
            model_name='imagechoice',
            name='ImageQuestion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='question.imagequestion'),
            preserve_default=False,
        ),
    ]
