# Generated by Django 3.1.2 on 2020-11-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0016_auto_20201103_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagechoice',
            name='img',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='画像'),
        ),
    ]
