# Generated by Django 3.1.2 on 2020-11-03 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0017_auto_20201103_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='avator',
        ),
    ]
