# Generated by Django 3.1.2 on 2020-11-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0020_auto_20201105_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='画像'),
        ),
    ]
